// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-2",
    "aws_content_delivery_bucket": "cockpit-20181003155932--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "http://cockpit-20181003155932--hostingbucket.s3-website.ap-northeast-2.amazonaws.com"
};


export default awsmobile;
