// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-2:d9a52d85-ed69-4330-8093-c0c55875de84',
    'aws_cognito_region': 'ap-northeast-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'kandala-hosting-mobilehub-1152976885',
    'aws_content_delivery_bucket_region': 'ap-northeast-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2tzkfty4qvirk.cloudfront.net',
    'aws_mobile_analytics_app_id': '19cdfb69812e4b659d752b438fb20be0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '88975d41-8472-4835-9dcb-3fbedc4bfb30',
    'aws_project_name': 'Kandala',
    'aws_project_region': 'ap-northeast-2',
    'aws_resource_name_prefix': 'kandala-mobilehub-1152976885',
}

export default awsmobile;
